# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FirstMainWin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWin(object):
    def setupUi(self, MainWin):
        MainWin.setObjectName("MainWin")
        MainWin.resize(595, 503)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/TitleIcon/rc/清单.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWin.setWindowIcon(icon)
        self.menu = QtWidgets.QTabWidget(MainWin)
        self.menu.setGeometry(QtCore.QRect(0, 0, 591, 501))
        self.menu.setObjectName("menu")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 30, 511, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gridLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(0, 80, 591, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(50, 110, 491, 301))
        self.textBrowser.setObjectName("textBrowser")
        self.time_label_2 = QtWidgets.QLabel(self.tab)
        self.time_label_2.setGeometry(QtCore.QRect(340, 430, 221, 31))
        self.time_label_2.setText("")
        self.time_label_2.setObjectName("time_label_2")
        self.menu.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.line_2 = QtWidgets.QFrame(self.tab_3)
        self.line_2.setGeometry(QtCore.QRect(0, 80, 581, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_2.setGeometry(QtCore.QRect(50, 110, 491, 301))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.time_label = QtWidgets.QLabel(self.tab_3)
        self.time_label.setGeometry(QtCore.QRect(340, 430, 221, 31))
        self.time_label.setText("")
        self.time_label.setObjectName("time_label")
        self.layoutWidget = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 30, 511, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.menu.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.time_label_3 = QtWidgets.QLabel(self.tab_2)
        self.time_label_3.setGeometry(QtCore.QRect(340, 430, 221, 31))
        self.time_label_3.setText("")
        self.time_label_3.setObjectName("time_label_3")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_3.setGeometry(QtCore.QRect(50, 110, 491, 301))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setGeometry(QtCore.QRect(0, 80, 591, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 30, 511, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.menu.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab_4)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 581, 471))
        self.calendarWidget.setObjectName("calendarWidget")
        self.menu.addTab(self.tab_4, "")

        self.retranslateUi(MainWin)
        self.menu.setCurrentIndex(2)
        self.lineEdit_3.textChanged['QString'].connect(self.textBrowser_3.append)
        QtCore.QMetaObject.connectSlotsByName(MainWin)

    def retranslateUi(self, MainWin):
        _translate = QtCore.QCoreApplication.translate
        MainWin.setWindowTitle(_translate("MainWin", "清单List"))
        self.label.setText(_translate("MainWin", "添加已完成的任务："))
        self.menu.setTabText(self.menu.indexOf(self.tab), _translate("MainWin", "昨天"))
        self.label_2.setText(_translate("MainWin", "添加今天的任务：  "))
        self.menu.setTabText(self.menu.indexOf(self.tab_3), _translate("MainWin", "今天"))
        self.label_3.setText(_translate("MainWin", "添加明天的任务：  "))
        self.menu.setTabText(self.menu.indexOf(self.tab_2), _translate("MainWin", "明天"))
        self.menu.setTabText(self.menu.indexOf(self.tab_4), _translate("MainWin", "日 历"))
import icon_rc_rc
